### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ccxt==1.21.22 ERROR: No matching distribution found for ccxt==1.21.22

### ISSUE THREAD

**Issue by chaitshar** [jpmorganchase/python-training#44]
I was trying to run the binder linked to this repository and it seems like the version 1.21.22 of ccxt isn't available for installation. Is there a way to get the binder working by fiddling around with the requirements.txt ?

**Comment by Trailingslashes** [comment]
I got the same error:

`ERROR: No matching distribution found for ccxt==1.21.22
Removing intermediate container 49f57b1a96a4
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "binder/requirements.txt"' returned a non-zero code: 1Built image, launching...`
