### ISSUE TITLE
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### ISSUE THREAD

**Issue by LewisZWang** [jpmorganchase/python-training#52]
The error on the topic occurs with 'suggestions' shown above,

`To fix this you could try to:

loosen the range of package versions you've specified
remove package versions to allow pip attempt to solve the dependency conflict`

Could anyone have solutions to fix this Error? thx~

**Comment by Rein17** [comment]
What is the solutions to above error?

**Comment by timkpaine** [comment]
Duplicate
