### ISSUE TITLE
"Infinite" loop in post build

### ISSUE THREAD

**Issue by rgaiacs** [jpmorganchase/python-training#74]
Hi,

I'm one of the maintainers of mybinder.org.

I noticed that this repository has a long build time (longer than 1 hour).

I think this is related with https://github.com/jpmorganchase/python-training/blob/main/binder/postBuild#L8

Can you help me understand why the "infinite" loop?

**Comment by timkpaine** [comment]
@rgaiacs it used to be unstable to install extensions, I can change this but I no longer have merge rights on this repo

**Comment by rgaiacs** [comment]
Thanks @timkpaine and @t3rryM for the help.
